theme: jekyll-theme-time-machine
title: Abhishek's Resume
description: This is Abhishek's resume website hosted on GitHub Pages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://abhiintheweb.github.io" # the base hostname & protocol for your site